const $=id=>document.getElementById(id),key='537-rally-v1';
const launch=(target,wait,march,offset=0)=>target+(offset-wait-march)*1000;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=t=>new Date(t).toISOString().slice(0,19).replace('T',' ');
function valid(s){return s&&typeof s.title==='string'&&s.title.length<=80&&Number.isFinite(s.target)&&s.target>=0&&s.target<4102444800000&&Number.isInteger(s.waves)&&s.waves>=1&&s.waves<=10&&Number.isFinite(s.gap)&&s.gap>=1&&s.gap<=3600&&Array.isArray(s.players)&&s.players.length>=1&&s.players.length<=50&&s.players.every(p=>typeof p.name==='string'&&p.name.length<=40&&Number.isFinite(p.march)&&p.march>=0&&p.march<=3600&&[0,60,120,300,600].includes(p.wait)&&Number.isFinite(p.offset)&&Math.abs(p.offset)<=300)}
let state={title:'537 王城・砲台集結',target:Math.ceil((Date.now()+720000)/10000)*10000,waves:1,gap:30,players:[{name:'ニクシー',march:43,wait:300,offset:0},{name:'プレイヤー A',march:60,wait:300,offset:0},{name:'プレイヤー B',march:36,wait:300,offset:0}]};
try{let s=JSON.parse(localStorage.getItem(key));if(valid(s))state=s}catch{}
try{if(location.hash.startsWith('#plan=')){let s=JSON.parse(decodeURIComponent(location.hash.slice(6)));if(valid(s))state=s;else throw Error()}}catch{notify('共有データを読み込めませんでした')}
function notify(t){$('notice').textContent=t;setTimeout(()=>$('notice').textContent='',4000)}
function persist(){try{localStorage.setItem(key,JSON.stringify(state))}catch{} }
function inputs(){$('title').value=state.title;$('utcHour').value=stamp(state.target).slice(11,13);$('utcMinute').value=stamp(state.target).slice(14,16);$('utcSecond').value=stamp(state.target).slice(17,19);
$('players').innerHTML=state.players.map((p,i)=>`<div class="player"><div class="player-head"><input aria-label="プレイヤー名" maxlength="40" data-i="${i}" data-k="name" value="${esc(p.name)}"><button class="remove" aria-label="プレイヤー削除" data-remove="${i}">×</button></div><div class="triple"><label>行軍（秒）<input type="number" min="0" max="3600" data-i="${i}" data-k="march" value="${p.march}"></label><label>集結待機<select data-i="${i}" data-k="wait">${[[0,'単身攻撃'],[60,'1分'],[120,'2分'],[300,'5分'],[600,'10分']].map(([v,n])=>`<option value="${v}" ${v===p.wait?'selected':''}>${n}</option>`).join('')}</select></label><label>到着差（秒）<input type="number" min="-300" max="300" data-i="${i}" data-k="offset" value="${p.offset}"></label></div></div>`).join('');render()}
function rows(w){return state.players.map((p,i)=>({...p,i,arrival:state.target+w*state.gap*1000+p.offset*1000,start:launch(state.target+w*state.gap*1000,p.wait,p.march,p.offset)})).sort((a,b)=>a.start-b.start)}
function render(){state.waves=1;persist();$('plainText').value=planText();$('operation').textContent=state.title||'537 集結作戦';$('summary').textContent=`${state.players.length}人 · 同時着弾`;
$('schedule').innerHTML=Array.from({length:state.waves},(_,w)=>`<section class="card"><div class="wave-header"><h2>発起スケジュール</h2><span>${stamp(state.target).slice(11)} UTC</span></div><div class="tablewrap"><table><thead><tr><th>プレイヤー</th><th>発起 / 攻撃出発 UTC</th><th>到着 UTC</th><th>あと</th></tr></thead><tbody>${rows(w).map(p=>`<tr><td><b>${esc(p.name||'名前未設定')}</b><div class="meta">${p.wait?p.wait/60+'分集結':'単身'} · 行軍${p.march}秒${p.offset?' · '+(p.offset>0?'+':'')+p.offset+'秒':''}</div></td><td class="time">${stamp(p.start).slice(11)}</td><td>${stamp(p.arrival).slice(11)}</td><td class="count" data-start="${p.start}"></td></tr>`).join('')}</tbody></table></div>${rows(w).some(p=>p.start<Date.now())?'<p class="warning">発起時刻を過ぎたプレイヤーがいます。必要なら到着目標を変更してください。</p>':''}</section>`).join('');tick()}
function tick(){$('clock').textContent=stamp(Date.now()).slice(11)+' UTC';document.querySelectorAll('[data-start]').forEach(el=>{let d=Math.ceil((Number(el.dataset.start)-Date.now())/1000);el.textContent=d<0?'時刻経過':d===0?'今すぐ':`${Math.floor(d/3600)?Math.floor(d/3600)+':':''}${String(Math.floor(d%3600/60)).padStart(2,'0')}:${String(d%60).padStart(2,'0')}`;el.className='count '+(d<0?'past':d<=10?'soon':'')})}
$('players').addEventListener('change',e=>{let k=e.target.dataset.k,i=Number(e.target.dataset.i);if(!k)return;let value=k==='name'?e.target.value:Number(e.target.value);let next=structuredClone(state);next.players[i][k]=value;if(!valid(next)){notify('入力範囲を確認してください');inputs();return}state=next;render()});
$('players').addEventListener('click',e=>{if(e.target.dataset.remove!==undefined){if(state.players.length===1)return notify('1人以上登録してください');state.players.splice(Number(e.target.dataset.remove),1);inputs()}});
$('add').onclick=()=>{if(state.players.length>=50)return notify('最大50人です');state.players.push({name:'プレイヤー '+(state.players.length+1),march:60,wait:300,offset:0});inputs()};
$('title').onchange=()=>{state.title=$('title').value;render()};
function nextUtc(h,m,s,now=Date.now()){if([h,m,s].some(v=>String(v).trim()===''))return NaN;let nums=[h,m,s].map(Number);if(nums.some((n,i)=>!Number.isInteger(n)||n<0||n>(i===0?23:59)))return NaN;let d=new Date(now);d.setUTCHours(...nums,0);if(d.getTime()<now)d.setUTCDate(d.getUTCDate()+1);return d.getTime()}
['utcHour','utcMinute','utcSecond'].forEach(id=>$(id).onchange=()=>{let t=nextUtc($('utcHour').value,$('utcMinute').value,$('utcSecond').value);let next={...state,target:t};if(!valid(next)){notify('UTCの時・分・秒を確認してください');inputs();return}state=next;render()});
const shiftUtc=(target,seconds)=>target+seconds*1000;
document.querySelectorAll('[data-shift]').forEach(button=>button.onclick=()=>{let next={...state,target:shiftUtc(state.target,Number(button.dataset.shift))};if(!valid(next))return notify('設定できる日付の範囲を超えています');state=next;inputs()});
$('now').onclick=()=>{state.target=Math.floor(Date.now()/1000)*1000;inputs()};
$('auto').onclick=()=>{state.target=Math.ceil((Date.now()+60000+Math.max(...state.players.map(p=>p.wait+p.march-p.offset))*1000)/10000)*10000;inputs()};
async function copy(t){try{await navigator.clipboard.writeText(t);notify('コピーしました')}catch{notify('コピーできません。表示した文章を選択してください');let box=document.createElement('textarea');box.value=t;box.style.width='100%';$('notice').append(box);box.select()}}
function planText(){const waits=[...new Set(state.players.map(p=>p.wait))];const mixed=waits.length>1;const rallyLabel=wait=>wait?wait/60+'分':'単身攻撃';return '【＃537 集結指示 UTC】\n作戦名：'+(state.title||'537 集結')+'\n集結時間：'+(mixed?'各行に記載':rallyLabel(waits[0]))+'\n目標着弾：'+stamp(state.target).slice(11)+' UTC\n\n'+rows(0).map(p=>`${p.name||'名前未設定'} → ${stamp(p.start).slice(11)}${mixed?'（'+rallyLabel(p.wait)+'）':p.wait===0?'（出発）':''}${p.offset?' ／ '+Math.abs(p.offset)+'秒'+(p.offset>0?'後着':'先着'):''}`).join('\n')}
$('copy').onclick=$('copyText').onclick=()=>copy(planText());
$('share').onclick=()=>copy(location.origin+location.pathname+'#plan='+encodeURIComponent(JSON.stringify(state)));
state.waves=1;inputs();setInterval(tick,250);
